### ISSUE TITLE
Indefinitely loading instead of suggestions

### ISSUE THREAD

**Issue by vknabel** [vknabel/vscode-swift-development-environment#112]
> Hey, @vknabel, looks like SDE 2.12.2 has no issues with starting up and running, so the bug appears to be fixed! I am seeing a problem with hover help getting stuck (at "Loading...") with SDE whereas they work with the plain sourcekit-LSP and extension, but that may well be an operator error (configuration problem). Unless you want to track that here, I suggest closing and I'll continue working on that separately...

from https://github.com/vknabel/vscode-swift-development-environment/issues/111#issuecomment-950237972 by @fphartnc

**Comment by fphartnc** [comment]
Update:  I now have uninstalled version 1.61.2 and done a fresh installation of version 1.60.2, and I seem to be back to where I was at the time this issue was opened:  Sourcekit-LSP seems to work just fine on my standalone swift file, showing hover hints.  But SDE/sourcekite shows "Loading..."  One other thing I can report:  Down in the lower left status area, I am seeing a message that says "building" alongside a progress indicator (of a sort I haven't seen in the past).  Question:  Is there a possibility that SDE/sourcekite is being blocked until the "build" takes place?  Note here that I do not have a swift "build" task defined yet... I will get to doing that in the next day or so, but other scheduled weekend activities will put this on hold...

**Comment by vknabel** [comment]
Thanks for the updates! I won't have access to a laptop for about a week, but I'd be happy to help.

SDE works best for Swift Package Manager projects. In those cases it should work relatively well for Linux and macOS projects. iOS, Tensorflow for Swift and others require some additional setup.

SDE will now automatically build your SwiftPM targets. That creates an index of your source code and typings for sourcekite and sourcekit-lsp. After that successful build, intelli sense should work fine.

The building indicates this process. If there are compile errors it show something like failed.
