### ISSUE TITLE
Sourcekite code: -32603 

### ISSUE THREAD

**Issue by Lavmint** [vknabel/vscode-swift-development-environment#73]
I successfully configured vscode to run with sourcekit-lsp, however it is extremely slow and I wanted to try sourcekite so I added path to sourcekite and changed mode but getting on every edit:
```
[Error - 1:16:57 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot call write after a stream was destroyed
  Code: -32603 
```
sde: 2.10
vscode:
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64

**Comment by haifengkao** [comment]
I know sourcekit-lsp is very slow, so I made a faster version
https://github.com/haifengkao/fast-sourcekit-lsp/releases
The problem of sourcekit-lsp is that it will return all symbols for every keystroke.  I add pre-filtering to remove the symbols which do not match the text typed before the cursor.

I don't use sourcekite, though.

**Comment by haifengkao** [comment]
I push all my changes to master branch. I do not touch any other branches. 
In fact, the changes are almost in this commit (https://github.com/haifengkao/fast-sourcekit-lsp/commit/3177e21234942ec7db4ed5bb96057700e33c86d1)

```
upd: there is no deference with libs of without, it depend on imports.
FoundationNetworking is fast
Foundation is slow
```
That's correct, because original sourcekit will return ALL symbols to vscode. If the header has a lot of symbols(> 10k), it will be very slow. All I did is removing the irrelevant symbols before sending them to vscode.
