### ISSUE TITLE
Add command to restart the LSP

### ISSUE THREAD

**Issue by clayreimann** [vknabel/vscode-swift-development-environment#82]
I've noticed that sometimes when I add code I get the language server stuck and wind up with errors about not finding modules or functions. In such cases if I restart the extension host (which restarts the LSP) things go back to normal. However that restarts _all_ extensions running in VSCode and is rather heavy weight.

![image](https://user-images.githubusercontent.com/930039/97828730-f4efe780-1c95-11eb-8e51-30be5404d86a.png)

The VSCode golang extension has a handy option to restart the language server, and I think it'd be cool if this extension had a similar option.

**Comment by vknabel** [comment]
Hi @clayreimann, great suggestion!

This will probably require some refactorings, but opens up lots of great improvements.

**Comment by clayreimann** [comment]
@vknabel any pointers on where I can look to start this?

**Comment by vknabel** [comment]
Hi @clayreimann, sorry for the late response. I'd be happy to see a PR! Thanks for considering.

Not sure if you have already seen it: the [CONTRIBUTING.md](https://github.com/vknabel/vscode-swift-development-environment/blob/master/CONTRIBUTING.md) gives a little bit of context. Though not a lot. 😅

Not sure regarding your background in VS Code extensions. This project uses yarn instead of npm, it also uses prettier to format code. The debugger settings should already be set up in VS Code.

Essentially this feature is about adding a new command to the package.json. The rest is currently implemented in [src/clientMain.ts](https://github.com/vknabel/vscode-swift-development-environment/blob/master/src/clientMain.ts):

In `activate` the command to restart must be registered (`commands.registerCommand`).
In there all subscriptions added to the `ExtensionContext` must be disposed.

Thereafter you should be able to call `activate` again. If I didn't forget anything, that's it.

Don't hesitate to ask any questions. The clientMain.ts file isn't in best shape and is quite hacky. I'll try to answer much faster next time 😊

**Comment by vknabel** [comment]
Thanks a lot @clayreimann for your great work and effort you put into your PR!
